<?php

/*
 * This file is part of the Daw package.
 *
 * (c) Axel Tessier <axel.tessier@extendev.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Daw\Modules\Skeleton;

/**
 * Skeleton Module base class
 *
 * @package daw
 * @subpackage ModuleSkeleton
 * @author Axel Tessier <axel.tessier@extendev.net>
 * @version $Id$
 */
class Module extends \Daw\Core\Module\Module {
}
