<?php

/**
 * This file is part of the Daw package.
 *
 * (c) Axel Tessier <axel.tessier@extendev.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Daw\Core\Provider\Security\Exception;


/**
 * Daw - Exception Base Class
 *
 * All exceptions raised by the application and modules
 * shall extend this exception to be properly formatted
 * by the different services
 *
 * @author Axel Tessier / Extendev
 * @version $Id$
 */
class AuthenticationException extends \Daw\Core\Exception\Exception {
}
